# Generated by Django 4.0.1 on 2022-01-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
