# Generated by Django 4.0.1 on 2022-01-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Nom du projet')),
                ('project_duration', models.IntegerField(default=0, verbose_name='Duree estimee')),
                ('time_allocated', models.IntegerField(verbose_name='Temps alloue')),
                ('needs', models.TextField(max_length=100, verbose_name='Besoins')),
                ('desc', models.TextField(max_length=250, verbose_name='description')),
                ('isValid', models.BooleanField(default=False)),
            ],
        ),
    ]
