# Generated by Django 4.0.1 on 2022-01-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project_Owner', to='hub.student'),
        ),
    ]
