# Generated by Django 3.2 on 2022-02-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_project_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipInProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_allocated', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.student')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='Les_membres', through='hub.MembershipInProjects', to='hub.Student'),
        ),
    ]
