# Generated by Django 3.2 on 2022-02-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20220207_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipinprojects',
            options={'verbose_name_plural': 'Memberships'},
        ),
    ]
